;;; kanagawa-theme.el --- Kanagawa theme for Doom Emacs -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; Author: OpenCode Agent
;; Source: https://github.com/rebelot/kanagawa.nvim
;;
;;; Commentary:
;;  A dark theme based on the Kanagawa.nvim theme with canonical palette.
;;
;;; Code:

;; (require 'doom-themes)

;; (defconst kanagawa-palette
;;   '((fujiWhite    . "#DCD7BA")
;;     (oldWhite     . "#C8C093")
;;     (sumiInk0     . "#16161D")
;;     (sumiInk1     . "#1F1F28")
;;     (sumiInk2     . "#2A2A37")
;;     (sumiInk3     . "#363646")
;;     (sumiInk4     . "#54546D")
;;     (waveBlue1    . "#223249")
;;     (waveBlue2    . "#2D4F67")
;;     (winterGreen  . "#2B3328")
;;     (winterYellow . "#49443C")
;;     (winterRed    . "#43242B")
;;     (winterBlue   . "#252535")
;;     (autumnGreen  . "#76946A")
;;     (autumnRed    . "#C34043")
;;     (autumnYellow . "#DCA561")
;;     (samuraiRed   . "#E82424")
;;     (roninYellow  . "#FF9E3B")
;;     (waveAqua1    . "#6A9589")
;;     (dragonBlue   . "#658594")
;;     (fujiGray     . "#727169")
;;     (springViolet1 . "#938AA9")
;;     (oniViolet    . "#957FB8")
;;     (crystalBlue  . "#7E9CD8")
;;     (springViolet2 . "#9CABCA")
;;     (springBlue   . "#7FB4CA")
;;     (lightBlue    . "#A3D4D5")
;;     (waveAqua2    . "#7AA89F")
;;     (springGreen  . "#98BB6C")
;;     (boatYellow1  . "#938056")
;;     (boatYellow2  . "#C0A36E")
;;     (carpYellow   . "#E6C384")
;;     (sakuraPink   . "#D27E99")
;;     (waveRed      . "#E46876")
;;     (peachRed     . "#FF5D62")
;;     (surimiOrange . "#FFA066")
;;     (katanaGray   . "#717C7C")))

;; (def-doom-theme doom-kanagawa
;;   "A dark theme inspired by Kanagawa.nvim, using the canonical palette."
;;   ;; Palette
;;   ((bg         (cdr (assoc 'sumiInk1 kanagawa-palette)))
;;    (bg-alt     (cdr (assoc 'sumiInk2 kanagawa-palette)))
;;    (base0      (cdr (assoc 'sumiInk0 kanagawa-palette)))
;;    (base1      (cdr (assoc 'sumiInk1 kanagawa-palette)))
;;    (base2      (cdr (assoc 'sumiInk2 kanagawa-palette)))
;;    (base3      (cdr (assoc 'sumiInk3 kanagawa-palette)))
;;    (base4      (cdr (assoc 'sumiInk4 kanagawa-palette)))
;;    (base5      (cdr (assoc 'fujiGray kanagawa-palette)))
;;    (base6      (cdr (assoc 'katanaGray kanagawa-palette)))
;;    (base7      (cdr (assoc 'oldWhite kanagawa-palette)))
;;    (base8      (cdr (assoc 'fujiWhite kanagawa-palette)))
;;    (fg         (cdr (assoc 'fujiWhite kanagawa-palette)))
;;    (fg-alt     (cdr (assoc 'oldWhite kanagawa-palette)))
;;    (grey       base5)
;;    (red        (cdr (assoc 'samuraiRed kanagawa-palette)))
;;    (orange     (cdr (assoc 'surimiOrange kanagawa-palette)))
;;    (green      (cdr (assoc 'springGreen kanagawa-palette)))
;;    (teal       (cdr (assoc 'waveAqua2 kanagawa-palette)))
;;    (yellow     (cdr (assoc 'carpYellow kanagawa-palette)))
;;    (blue       (cdr (assoc 'crystalBlue kanagawa-palette)))
;;    (dark-blue  (cdr (assoc 'waveBlue2 kanagawa-palette)))
;;    (magenta    (cdr (assoc 'springViolet1 kanagawa-palette)))
;;    (violet     (cdr (assoc 'oniViolet kanagawa-palette)))
;;    (cyan       (cdr (assoc 'lightBlue kanagawa-palette)))
;;    (dark-cyan  (cdr (assoc 'waveAqua1 kanagawa-palette)))
;;    (highlight      blue)
;;    (vertical-bar   base1)
;;    (selection      dark-blue)
;;    (builtin        magenta)
;;    (comments       base5)
;;    (doc-comments   base6)
;;    (constants      yellow)
;;    (functions      blue)
;;    (keywords       violet)
;;    (methods        cyan)
;;    (operators      orange)
;;    (type           yellow)
;;    (strings        green)
;;    (variables      magenta)
;;    (numbers        orange)
;;    (region         dark-blue)
;;    (error          red)
;;    (warning        yellow)
;;    (success        green)
;;    (vc-modified    orange)
;;    (vc-added       green)
;;    (vc-deleted     red)
;;    ;; Modeline colors
;;    (modeline-fg              fg)
;;    (modeline-fg-alt          base5)
;;    (modeline-bg              bg-alt)
;;    (modeline-bg-alt          base2)
;;    (modeline-bg-inactive     base1)
;;    (modeline-bg-inactive-alt base2))
;;   ;; Faces
;;   ((default :background bg :foreground fg)
;;    (region  :background region)
;;    (highlight :background highlight :foreground fg)
;;    (vertical-border :foreground base4)
;;    (error :foreground error)
;;    (warning :foreground warning)
;;    (success :foreground success)
;;    ((line-number &override) :foreground base5 :background bg)
;;    ((line-number-current-line &override) :foreground blue :background bg :weight 'bold)
;;    (mode-line :background base4 :foreground fg :box nil)
;;    (mode-line-inactive :background base2 :foreground base5 :box nil)
;;    (mode-line-emphasis :foreground highlight :background base4)
;;    (mode-line-buffer-id :foreground highlight :bold t :background base4)
;;    (doom-modeline-bar :background base4)
;;    (doom-modeline-buffer-modified :foreground orange :background base4)
;;    (doom-modeline-buffer-path :foreground blue :weight 'normal :background base4)
;;    (doom-modeline-buffer-file :foreground fg :weight 'normal :background base4)
;;    (doom-modeline-project-dir :foreground violet :weight 'normal :background base4)
;;    (doom-modeline-project-root-dir :foreground violet :weight 'normal :background base4)
;;    (doom-modeline-highlight :foreground blue :background base4)
;;    (doom-modeline-panel :background base4 :foreground fg)
;;    (doom-modeline-evil-normal-state :foreground green :background base4)
;;    (doom-modeline-evil-insert-state :foreground blue :background base4)
;;    (doom-modeline-evil-visual-state :foreground magenta :background base4)
;;    (hl-line :background base2)
;;    (ivy-current-match :background base2 :foreground fg :weight 'bold)
;;    (ivy-minibuffer-match-face-1 :foreground blue :background bg)
;;    (ivy-minibuffer-match-face-2 :foreground orange :background bg)
;;    (ivy-minibuffer-match-face-3 :foreground green :background bg)
;;    (ivy-minibuffer-match-face-4 :foreground yellow :background bg)
;;    (vertico-current :background base2 :foreground fg :weight 'bold)
;;    (solaire-hl-line-face :background base2)
;;    (solaire-region-face :background base2)
;;    (solaire-mode-line-face :inherit 'mode-line :background base2)
;;    (solaire-mode-line-inactive-face :inherit 'mode-line-inactive :background base1)
;;    (rainbow-delimiters-depth-1-face :foreground fg :background bg)
;;    (rainbow-delimiters-depth-2-face :foreground blue :background bg)
;;    (rainbow-delimiters-depth-3-face :foreground orange :background bg)
;;    (rainbow-delimiters-depth-4-face :foreground green :background bg)
;;    (rainbow-delimiters-depth-5-face :foreground cyan :background bg)
;;    (rainbow-delimiters-depth-6-face :foreground yellow :background bg)
;;    (rainbow-delimiters-depth-7-face :foreground teal :background bg)
;;    (org-level-1 :foreground blue :weight 'bold :extend t :height 1.2 :background bg)
;;    (org-level-2 :foreground magenta :weight 'bold :extend t :height 1.15 :background bg)
;;    (org-level-3 :foreground green :weight 'bold :extend t :height 1.1 :background bg)
;;    (org-level-4 :foreground yellow :weight 'bold :extend t :height 1.05 :background bg)
;;    (org-level-5 :foreground violet :weight 'bold :extend t :background bg)
;;    (org-level-6 :foreground red :weight 'bold :extend t :background bg)
;;    (org-level-7 :foreground cyan :weight 'bold :extend t :background bg)
;;    (org-level-8 :foreground teal :weight 'bold :extend t :background bg)
;;    (org-todo :foreground orange :weight 'bold :background bg)
;;    (org-done :foreground green :weight 'bold :background bg)
;;    (org-headline-done :foreground base5 :strike-through t :background bg)
;;    (org-link :foreground teal :underline t :background bg)
;;    (org-code :foreground yellow :background bg)
;;    (org-special-keyword :foreground magenta :background bg)
;;    (org-block :background base2 :extend t)
;;    (org-block-begin-line :foreground base5 :background base2 :extend t)
;;    (org-block-end-line :foreground base5 :background base2 :extend t)
;;    (org-quote :foreground blue :background base2 :extend t)
;;    (org-table :foreground violet :background bg)
;;    (org-document-title :foreground cyan :weight 'bold :height 1.3 :background bg)
;;    (org-document-info :foreground cyan :background bg)
;;    (org-date :foreground magenta :background bg)
;;    (org-drawer :foreground base5 :background bg)
;;    (org-agenda-structure :foreground blue :background bg)
;;    (org-agenda-date :foreground fg :background bg)
;;    (org-agenda-date-today :foreground fg :weight 'bold :background bg)
;;    (org-scheduled :foreground fg :background bg)
;;    (org-scheduled-today :foreground fg :background bg)
;;    (org-scheduled-previously :foreground base5 :background bg)
;;    (org-upcoming-deadline :foreground orange :background bg)
;;    (org-deadline-announce :foreground red :background bg)
;;    (org-formula :foreground green :background bg)
;;    (org-tag :foreground cyan :weight 'normal :background bg)
;;    (org-checkbox :foreground blue :weight 'normal :background bg)
;;    (org-checkbox-statistics-todo :foreground blue :weight 'normal :background bg)
;;    (org-checkbox-statistics-done :foreground green :weight 'normal :background bg)
;;    (company-tooltip :background base2 :foreground fg)
;;    (company-tooltip-annotation :foreground cyan :background base2)
;;    (company-tooltip-annotation-selection :foreground cyan :weight 'bold :background base2)
;;    (company-tooltip-selection :background base2 :foreground fg :weight 'bold)
;;    (company-tooltip-common :foreground yellow :weight 'bold :background base2)
;;    (company-tooltip-common-selection :foreground yellow :weight 'bold :background base2)
;;    (company-scrollbar-bg :background base2)
;;    (company-scrollbar-fg :background base3)
;;    (company-preview :background base2 :foreground fg)
;;    (company-preview-common :foreground yellow :weight 'bold :background base2)
;;    (font-lock-keyword-face :foreground keywords)
;;    (font-lock-type-face :foreground type)
;;    (font-lock-string-face :foreground strings)
;;    (font-lock-function-name-face :foreground functions)
;;    (font-lock-variable-name-face :foreground variables)
;;    (font-lock-constant-face :foreground constants)
;;    (font-lock-comment-face :foreground comments :italic t)
;;    (font-lock-doc-face :foreground doc-comments :italic t)
;;    ))

;; ;;;###autoload
;; (when (and load-file-name (boundp 'custom-theme-load-path))
;;   (add-to-list 'custom-theme-load-path
;;                (file-name-as-directory
;;                 (file-name-directory load-file-name))))

;; (provide-theme 'doom-kanagawa)
;; ;;; kanagawa-theme.el ends here
